# This sets the status checks for commits to non-main branches so that a protected-branch check can be made
on:
  push:
    branches-ignore: ['master']
    paths: ['**', '!README.md', '!CHANGELOG.md', '!.gitignore']
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # SETUP START
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1200            # Clojure CLI based on tools.deps

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      #SETUP END

      # Run tests. If the tests fail, a Pull Request from the commit can't be merged to a protected branch.
      - name: Run tests
        run: clojure -X:test
