# Publish releases to Clojars
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # SETUP START
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1200            # Clojure CLI based on tools.deps

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      # SETUP END

      - name: Build pipeline
        run: >-
          clojure -X:build pipeline :lib io.github.mortenschioler/loco :version '"${{github.ref_name}}"'
        env:
          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}
          CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
